=== MouhtaramSoufiane/XML-dtd-shemasXML/shemaOP.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
<xsd:element name="operateur">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="client" minOccurs="1" maxOccurs="unbounded" type="TYPE_CL"></xsd:element>
        </xsd:sequence>
        
    </xsd:complexType>
</xsd:element>
<xsd:complexType name="TYPE_CL">
    <xsd:sequence>
        <xsd:element name="abonnement" minOccurs="1" maxOccurs="unbounded" type="TYPE_ABO"></xsd:element>
    </xsd:sequence>
    <xsd:attribute name="code" type="xsd:int" use="required"></xsd:attribute>
    <xsd:attribute name="nom" type="xsd:string" use="required"></xsd:attribute>
</xsd:complexType>
<xsd:complexType name="TYPE_ABO">
    <xsd:sequence>
        <xsd:element name="facteur" minOccurs="1" maxOccurs="unbounded" type="TYPE_FACT"></xsd:element>
    </xsd:sequence>
    <xsd:attribute name="numero" type="xsd:string" use="required"></xsd:attribute>
    <xsd:attribute name="dateAbo" type="xsd:date" use="required"></xsd:attribute>
    <xsd:attribute name="type" >
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="GSM"></xsd:enumeration>
                <xsd:enumeration value="FIXE"></xsd:enumeration>
                <xsd:enumeration value="INTERNET"></xsd:enumeration>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:attribute>
</xsd:complexType>
<xsd:complexType name="TYPE_FACT">
    <xsd:attribute name="num" type="xsd:string" use="required"></xsd:attribute>
    <xsd:attribute name="DateFact" type="xsd:date" use="required"></xsd:attribute>
    <xsd:attribute name="montant" type="xsd:double"></xsd:attribute>
    <xsd:attribute name="regle" default="Non">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="Non"></xsd:enumeration>
                <xsd:enumeration value="Oui"></xsd:enumeration>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:attribute>
</xsd:complexType>
   
</xsd:schema>

=== MouhtaramSoufiane/XML-dtd-shemasXML/operateur.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="operateur1.xsl"?>
<operateur xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Daaif_Xml/shemaOP.xsd">
    <client code="123" nom="Mouhtaram" >
        <abonnement numero="001" dateAbo="2023-03-11" type="GSM">
            <facteur num="011" DateFact="2023-03-11" montant="500.5" regle="Oui"/>
            <facteur num="033" DateFact="2023-03-12" regle="Oui" montant="400.5"/>
        </abonnement>
        <abonnement numero="002" dateAbo="2023-03-29" type="INTERNET">
            <facteur num="066" DateFact="2023-03-29" montant="900" regle="Oui"/>
        </abonnement>
    </client>
    <client code="456" nom="Haissouni">
        <abonnement numero="111" dateAbo="2023-03-30" type="FIXE" >
            <facteur num="22" DateFact="2023-03-30" montant="200" regle="Oui"/>
        </abonnement>
        <abonnement numero="678" dateAbo="2023-04-29" type="INTERNET">
            <facteur num="37" DateFact="2023-04-30" regle="Oui" montant="600.9"/>
            <facteur num="56" DateFact="2023-05-30" regle="Non" montant="500.9"/>
        </abonnement>
    </client>
</operateur>
